[package]
name = "g3-route-transitions-playground"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dioxus = { version = "=0.7.9", features = ["router", "web"] }
g3-route-transitions = { path = ".." }
gloo-timers = { version = "0.3", features = ["futures"] }
manganis = "=0.7.9"

[features]
default = ["web"]
web = ["dioxus/web"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[target.wasm32-unknown-unknown.dependencies.getrandom_v03]
package = "getrandom"
version = "0.3.3"
features = ["wasm_js"]
